### ISSUE TITLE
ZBD API Integration with Trigger.dev

### ISSUE THREAD

**Issue by andrerfneves** [zebedeeio/trigger.dev#2]
# Task

Integrate the [Send to Lightning Address API](https://zbd.dev/api-reference/lightning-address/send) as a Trigger.dev integration package. To read more about Trigger.dev Integrations [read this](https://trigger.dev/docs/integrations/create): https://trigger.dev/docs/integrations/create. The idea is to be able to run ZBD payments from inside a Trigger.dev job by calling `const response = await io.zbd.sendLightningAddressPayment()` (or something of the sort).

**Part of the integration code has been added on PR https://github.com/zebedeeio/trigger.dev/pull/1 but it has not been finalized nor tested.**

## Deliverables

- [ ] Codebase ready to be submitted as a PR to the [upstream repository for Trigger.dev](https://github.com/triggerdotdev/trigger.dev)
- [ ] ZBD API integrated into Trigger.dev jobs natively
- [ ] Integration test code is written and works
- [ ] Processes / requirements outlined on [Create Trigger.dev Integration](https://trigger.dev/docs/integrations/create) docs are followed

## Resources

- [zbd.dev](https://zbd.dev) -> ZBD API documentation and API reference
  - API Key for ZBD API: `bEIXXd3tbt1hbUAqQD0YXR9l0oI7hdBx`
- [Trigger.dev](https://trigger.dev) -> Background jobs runner

**Comment by andrerfneves** [comment]
Make sure to build upon the #1 PR: https://github.com/zebedeeio/trigger.dev/pull/1

**Comment by rishi-raj-jain** [comment]
/attempt #2

<details id="algora-options">
  <summary>Options</summary>
  <ul>
    <li>
      <a href="https://console.algora.io/api/bounties/clnpnl7a90002lc0f0rw7n7f4/cancel-attempt">
        Cancel my attempt
      </a>
    </li>
  </ul>
</details>

**Comment by XooTB** [comment]
/attempt #2

<details id="algora-options">
  <summary>Options</summary>
  <ul>
    <li>
      <a href="https://console.algora.io/api/bounties/clnpnl7a90002lc0f0rw7n7f4/cancel-attempt">
        Cancel my attempt
      </a>
    </li>
  </ul>
</details>

**Comment by mrkirthi-24** [comment]
Hey @rishi-raj-jain are you working on this??

**Comment by rishi-raj-jain** [comment]
@mrkirthi-24 

Feel free to take this...

**Comment by ishqDehlvi** [comment]
Hey @rishi-raj-jain @mrkirthi-24 Are you working on this??

**Comment by rajdip-b** [comment]
/attempt #2

<details id="algora-options">
  <summary>Options</summary>
  <ul>
    <li>
      <a href="https://console.algora.io/api/bounties/clnpnl7a90002lc0f0rw7n7f4/cancel-attempt">
        Cancel my attempt
      </a>
    </li>
  </ul>
</details>

**Comment by rajdip-b** [comment]
@andrerfneves hey, can you review the PR?

**Comment by shailedrathakur300** [comment]
/attempt #2

<div id="algora-attempt" />

<details>
  <summary>Options</summary>
  <ul>
    <li>
      <a href="https://console.algora.io/api/bounties/clnpnl7a90002lc0f0rw7n7f4/cancel-attempt">
        Cancel my attempt
      </a>
    </li>
  </ul>
</details>

**Comment by oliverqx** [comment]
@andrerfneves im confident i can tackle this, i've a lot of experience in blockchain development. I currently half time work at an l2 ethereum based company, and a couple years ago i was working in ethereum infrastructure development. I'm confident i can tackle this, but it looks like there was a solution before that was entirely ignored, and i've had many experiences like that with algora bounties before - where not even feedback is provided. 

The bounty is too low to take such a risk so i would just like some confirmation you would actually be looking at the solutions before i attempt one

**Comment by DailyInvestors** [comment]
HELLO, sorry about the missed attempts. I thought this was for something else. I'm not sure if you know me from ZBD, been a member for years now. I am in college, and I have taught myself javaScript, Python, and Json. And a select few others. I am a Cyber Security Specialist in training, and a pen tester. But hard times, especially with technology and being open-source, I have to make money. And being a supporter of ZBD, what better place then to build with you first of all. My business is slowly growing I guess. I'm with MooMoo and Simply Wall St now with a server, chats, etc, and a narrative for Simply. Now I wish to build with you.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by AgentGoose32** [comment]
/attempt #2

I have a local patch that updates the existing ZBD integration to the current Trigger.dev integration API, wires `sendLightningAddressPayment` through `io.runTask`, uses the exported `zbd` client from `@zbd/node`, and validates with `pnpm --filter @trigger.dev/zbd build` on Node 18.
